; ASCII source. Read-only inspection; no external COM attachment or DWG writes.
; Native entget is primary. Optional ActiveX getters add dynamic metadata in full mode.
(defun mep2:out (s / previousStage)
  (setq previousStage stage)
  (if full (setq stage "write-output"))
  (write-line s mep2:fh)
  (setq stage previousStage))
; Decimal output independent of zero suppression, without changing DIMZIN.
(defun mep2:decimal (n / s dot)
  (setq s (rtos n 2 6))
  (if (= (substr s 1 1) ".") (setq s (strcat "0" s)))
  (if (= (substr s 1 2) "-.") (setq s (strcat "-0" (substr s 2))))
  (setq dot (vl-string-search "." s))
  (if (not dot)
    (setq s (strcat s ".") dot (1- (strlen s))))
  (while (< (- (strlen s) dot 1) 6) (setq s (strcat s "0")))
  s)
; Preserve DXF list/dotted-pair structure, including coordinates nested in raw records.
(defun mep2:format (value / s tail)
  (cond
    ((= (type value) 'REAL) (mep2:decimal value))
    ((and value (listp value))
      (setq s (strcat "(" (mep2:format (car value))) tail (cdr value))
      (while (and tail (listp tail))
        (setq s (strcat s " " (mep2:format (car tail))) tail (cdr tail)))
      (if tail (setq s (strcat s " . " (mep2:format tail))))
      (strcat s ")"))
    (T (vl-prin1-to-string value))))
(defun mep2:val (label value)
  (mep2:out (strcat label "=" (mep2:format value))))
(defun mep2:class (e / o r)
  (setq o (vl-catch-all-apply 'vlax-ename->vla-object (list e)))
  (if (vl-catch-all-error-p o)
    (strcat "UNAVAILABLE: " (vl-catch-all-error-message o))
    (progn
      (setq r (vl-catch-all-apply 'vla-get-ObjectName (list o)))
      (vl-catch-all-apply 'vlax-release-object (list o))
      (if (vl-catch-all-error-p r)
        (strcat "UNAVAILABLE: " (vl-catch-all-error-message r)) r))))
; Convert COM values without changing their CAD meaning. Preserve variant type separately.
(defun mep2:com-value (v)
  (cond
    ((= (type v) 'VARIANT) (mep2:com-value (vlax-variant-value v)))
    ((= (type v) 'SAFEARRAY) (mapcar 'mep2:com-value (vlax-safearray->list v)))
    (T v)))
(defun mep2:dynamic-field (obj prop label / raw value)
  (setq raw (vl-catch-all-apply 'vlax-get-property (list obj prop)))
  (if (vl-catch-all-error-p raw)
    (progn
      (setq dynamicPartial T)
      (mep2:val (strcat label "_Status") "unavailable")
      (mep2:val (strcat label "_Error") (vl-catch-all-error-message raw)))
    (progn
      (mep2:val (strcat label "_ValueType") (type raw))
      (if (= (type raw) 'VARIANT)
        (mep2:val (strcat label "_VariantType") (vlax-variant-type raw)))
      (setq value (vl-catch-all-apply 'mep2:com-value (list raw)))
      (if (vl-catch-all-error-p value)
        (progn (setq dynamicPartial T)
          (mep2:val (strcat label "_Status") "conversion_error")
          (mep2:val (strcat label "_Error") (vl-catch-all-error-message value)))
        (progn (mep2:val label value) (mep2:val (strcat label "_Status") "read")))))
  raw)
(defun mep2:dynamic-body (obj / dynamicFlag values prop key index)
  (mep2:dynamic-field obj 'EffectiveName "EffectiveName_RAW")
  (setq dynamicFlag (mep2:dynamic-field obj 'IsDynamicBlock "IsDynamicBlock"))
  (cond
    ((vl-catch-all-error-p dynamicFlag) (setq dynamicPartial T))
    ((= dynamicFlag :vlax-false) (mep2:val "DynamicPropertiesStatus" "not_dynamic"))
    ((= dynamicFlag :vlax-true)
      (setq values (vl-catch-all-apply 'vla-GetDynamicBlockProperties (list obj)))
      (if (vl-catch-all-error-p values)
        (progn (setq dynamicPartial T)
          (mep2:val "DynamicPropertiesStatus" "unavailable")
          (mep2:val "DynamicPropertiesError" (vl-catch-all-error-message values)))
        (progn
          (setq dynamicObjects (mep2:com-value values) index 0)
          (mep2:val "DynamicPropertyCount" (length dynamicObjects))
          (foreach prop dynamicObjects
            (mep2:val "DynamicProperty_BEGIN" index)
            (foreach key '(PropertyName Value AllowedValues UnitsType ReadOnly Description Show)
              (mep2:dynamic-field prop key (vl-symbol-name key)))
            (mep2:out "DynamicProperty_END")
            (setq index (1+ index)))
          (mep2:val "DynamicPropertiesStatus" "enumerated"))))
    (T (setq dynamicPartial T) (mep2:val "DynamicPropertiesStatus" "unknown_dynamic_flag"))))
(defun mep2:dynamic (e / obj result dynamicPartial dynamicObjects prop)
  (mep2:out "DynamicMetadata_BEGIN")
  (setq obj (vl-catch-all-apply 'vlax-ename->vla-object (list e)))
  (if (vl-catch-all-error-p obj)
    (progn
      (mep2:val "DynamicMetadataStatus" "unavailable")
      (mep2:val "DynamicMetadataError" (vl-catch-all-error-message obj)))
    (progn
      (setq result (vl-catch-all-apply 'mep2:dynamic-body (list obj)))
      (foreach prop dynamicObjects (vl-catch-all-apply 'vlax-release-object (list prop)))
      (vl-catch-all-apply 'vlax-release-object (list obj))
      (if (vl-catch-all-error-p result)
        (progn (mep2:val "DynamicMetadataStatus" "error")
          (mep2:val "DynamicMetadataError" (vl-catch-all-error-message result)))
        (mep2:val "DynamicMetadataStatus" (if dynamicPartial "partial" "read")))))
  (mep2:out "DynamicMetadata_END"))
(defun mep2:point (label p e / r)
  (mep2:val (strcat label "_OCS") p)
  (if p
    (progn
      (setq r (vl-catch-all-apply 'trans (list p e 0)))
      (if (vl-catch-all-error-p r)
        (progn
          (setq errors (1+ errors))
          (mep2:val "TRANSFORM_ERROR" (vl-catch-all-error-message r)))
        (mep2:val (strcat label "_WCS") r)))))
(defun mep2:text (d / s pair)
  (setq s "")
  (foreach pair d
    (if (= (car pair) 3) (setq s (strcat s (cdr pair)))))
  (strcat s (if (assoc 1 d) (cdr (assoc 1 d)) "")))
; Pure field maps: values are entget values (angles in radians), never roles.
; ATTRIB vertical alignment is DXF74, NOT TEXT's DXF73.
(defun mep2:layout-spec (typ)
  (cond
    ((equal typ "MTEXT")
      '(("Direction_WCS_RAW" 11) ("TextHeight" 40)
        ("ReferenceWidth" 41) ("AttachmentPoint" 71) ("TextStyle" 7)
        ("Normal" 210)))
    ((equal typ "ATTRIB")
      '(("Rotation" 50) ("TextHeight" 40) ("WidthFactor" 41)
        ("ObliqueAngle" 51) ("TextStyle" 7) ("HorizontalAlignment" 72)
        ("VerticalAlignment" 74) ("AlignmentPoint_OCS_RAW" 11) ("Normal" 210)))
    (T
      '(("Rotation" 50) ("TextHeight" 40) ("WidthFactor" 41)
        ("ObliqueAngle" 51) ("TextStyle" 7) ("HorizontalAlignment" 72)
        ("VerticalAlignment" 73) ("AlignmentPoint_OCS_RAW" 11) ("Normal" 210)))))
(defun mep2:layout-position (e d prefix / p r typ)
  (setq typ (cdr (assoc 0 d)) p (cdr (assoc 10 d)))
  (mep2:val (strcat prefix "Insertion_DXF10_RAW") p)
  (mep2:val (strcat prefix "InsertionRawFrame") (if (= typ "MTEXT") "WCS" "entity_ocs"))
  (setq r (if p (if (= typ "MTEXT") p (vl-catch-all-apply 'trans (list p e 0)))))
  (cond
    ((vl-catch-all-error-p r)
      (mep2:val (strcat prefix "positionFrame") "unknown")
      (mep2:val (strcat prefix "positionStatus") "conversion_error")
      (mep2:val (strcat prefix "positionError_RAW") (vl-catch-all-error-message r)))
    ((not r)
      (mep2:val (strcat prefix "positionFrame") "unknown")
      (mep2:val (strcat prefix "positionStatus") "missing_dxf10"))
    (T
      (mep2:val (strcat prefix "Position_WCS") r)
      (mep2:val (strcat prefix "positionFrame") "WCS")
      (mep2:val (strcat prefix "positionStatus") "read")))
  (if (and (/= typ "MTEXT") (assoc 11 d))
    (progn
      (setq r (vl-catch-all-apply 'trans (list (cdr (assoc 11 d)) e 0)))
      (if (vl-catch-all-error-p r)
        (progn
          (mep2:val (strcat prefix "AlignmentPointStatus") "conversion_error")
          (mep2:val (strcat prefix "AlignmentPointError_RAW") (vl-catch-all-error-message r)))
        (progn
          (mep2:val (strcat prefix "AlignmentPoint_WCS") r)
          (mep2:val (strcat prefix "AlignmentPointFrame") "WCS")
          (mep2:val (strcat prefix "AlignmentPointStatus") "read"))))))
; Called under a catch by bbox. COM output arrays are WCS, not OCS or INSERT local.
(defun mep2:bbox-body (obj / lo hi)
  (vla-GetBoundingBox obj 'lo 'hi)
  (list (mep2:com-value lo) (mep2:com-value hi)))
(defun mep2:point3-valid (p)
  (and (listp p) (= (length p) 3)
       (numberp (car p)) (numberp (cadr p)) (numberp (caddr p))))
(defun mep2:bbox-status (getterSucceeded validPoints)
  (cond ((not getterSucceeded) "unavailable")
        ((not validPoints) "invalid_result")
        (T "read")))
(defun mep2:bbox (e prefix / obj r status valid)
  (setq obj (vl-catch-all-apply 'vlax-ename->vla-object (list e)))
  (if (vl-catch-all-error-p obj)
    (setq r obj)
    (progn
      (setq r (vl-catch-all-apply 'mep2:bbox-body (list obj)))
      (vl-catch-all-apply 'vlax-release-object (list obj))))
  (setq valid
    (and (not (vl-catch-all-error-p r)) (listp r) (= (length r) 2)
         (mep2:point3-valid (car r)) (mep2:point3-valid (cadr r))
         (<= (caar r) (car (cadr r)))
         (<= (cadr (car r)) (cadr (cadr r)))
         (<= (caddr (car r)) (caddr (cadr r)))))
  (setq status (mep2:bbox-status (not (vl-catch-all-error-p r)) valid))
  (if (/= status "read")
    (progn
      (mep2:val (strcat prefix "bboxMin") nil)
      (mep2:val (strcat prefix "bboxMax") nil)
      (mep2:val (strcat prefix "bboxFrame") "unknown")
      (mep2:val (strcat prefix "bboxStatus") status)
      (mep2:val (strcat prefix "bboxError_RAW")
        (if (vl-catch-all-error-p r) (vl-catch-all-error-message r) "invalid WCS extents")))
    (progn
      (mep2:val (strcat prefix "bboxMin") (car r))
      (mep2:val (strcat prefix "bboxMax") (cadr r))
      (mep2:val (strcat prefix "bboxFrame") "WCS")
      (mep2:val (strcat prefix "bboxStatus") "read"))))
(defun mep2:layout-body (e d parent prefix / typ spec pair)
  (setq typ (cdr (assoc 0 d)))
  (mep2:val (strcat prefix "LayoutEntityHandle") (cdr (assoc 5 d)))
  (mep2:val (strcat prefix "LayoutEntityType") typ)
  (mep2:val (strcat prefix "ParentINSERTHandle") parent)
  (mep2:val (strcat prefix "AngleUnit") "radians")
  (if (= typ "MTEXT")
    (progn
      (mep2:val "Rotation" nil)
      (mep2:val "Rotation_Status" "not_interpreted_use_direction_vector")
      (mep2:val "DirectionFrame" "WCS")))
  (foreach spec (mep2:layout-spec typ)
    (setq pair (assoc (cadr spec) d))
    (mep2:val (strcat prefix (car spec)) (cdr pair))
    (mep2:val (strcat prefix (car spec) "_Status") (if pair "read" "absent_in_entget")))
  (foreach pair d
    (if (member (car pair) '(1 3 7 10 11 40 41 50 51 60 70 71 72 73 74 100 210))
      (mep2:val (strcat prefix "TextLayout_DXF") pair)))
  (if (= typ "ATTRIB")
    (progn
      (mep2:val (strcat prefix "Tag_RAW") (cdr (assoc 2 d)))
      (mep2:val (strcat prefix "Value_RAW") (mep2:text d))
      (mep2:val (strcat prefix "AttributeFlags_DXF70") (cdr (assoc 70 d)))
      (mep2:val (strcat prefix "VisibilityEvidence")
        (cond ((not (assoc 70 d)) "unknown")
              ((/= 0 (logand 1 (cdr (assoc 70 d)))) "attribute_invisible_flag")
              (T "attribute_not_flagged_hidden_not_final_visibility")))))
  (if (= typ "MTEXT") (mep2:val "rawMText" (mep2:text d)))
  (mep2:layout-position e d prefix)
  (mep2:bbox e prefix))
; Optional enrichment never increments the entity ReadErrorCount.
(defun mep2:text-layout (e d parent prefix / r)
  (mep2:out (strcat prefix "TextLayout_BEGIN"))
  (setq r (vl-catch-all-apply 'mep2:layout-body (list e d parent prefix)))
  (if (vl-catch-all-error-p r)
    (progn
      (mep2:val (strcat prefix "TextLayoutStatus") "error")
      (mep2:val (strcat prefix "TextLayoutError_RAW") (vl-catch-all-error-message r)))
    (mep2:val (strcat prefix "TextLayoutStatus") "completed_check_field_statuses"))
  (mep2:out (strcat prefix "TextLayout_END")))
(defun mep2:details (e d / typ pair pts p z sub sd flags obj b bd)
  (setq typ (cdr (assoc 0 d)))
  (mep2:val "ObjectName" (mep2:class e))
  (mep2:val "Normal_DXF210" (cdr (assoc 210 d)))
  (cond
    ((= typ "LINE")
      (mep2:val "Start_WCS" (cdr (assoc 10 d)))
      (mep2:val "End_WCS" (cdr (assoc 11 d))))
    ((= typ "LWPOLYLINE")
      (setq z (if (assoc 38 d) (cdr (assoc 38 d)) 0.0))
      (mep2:val "Flags_DXF70" (cdr (assoc 70 d)))
      (mep2:val "Closed" (= 1 (logand 1 (cdr (assoc 70 d)))))
      (mep2:val "Elevation" z)
      (foreach pair d
        (cond
          ((= (car pair) 10)
            (setq p (list (cadr pair) (caddr pair) z))
            (setq pts (cons p pts))
            (mep2:point "Vertex" p e))
          ((member (car pair) '(40 41 42 43))
            (mep2:val "Width_or_bulge_DXF" pair))))
      (setq pts (reverse pts))
      (mep2:point "FirstVertex" (car pts) e)
      (mep2:point "LastVertex" (last pts) e)
      (mep2:out "Closed paths connect last vertex to first; bulge belongs to preceding vertex."))
    ((= typ "POLYLINE")
      (setq flags (if (assoc 70 d) (cdr (assoc 70 d)) 0))
      (mep2:val "Flags_DXF70" flags)
      (mep2:val "HeaderPoint_DXF10" (cdr (assoc 10 d)))
      (mep2:val "Closed" (= 1 (logand 1 flags)))
      (mep2:out "Raw VERTEX records follow; mesh/polyface and fitted curves are not interpreted as cable paths.")
      (setq sub (entnext e))
      (while (and sub (/= "SEQEND" (cdr (assoc 0 (setq sd (entget sub))))))
        (mep2:val "Subentity_DXF" sd)
        (if (= "VERTEX" (cdr (assoc 0 sd)))
          (progn
            (setq p (cdr (assoc 10 sd)))
            (setq pts (cons p pts))
            (cond
              ((/= 0 (logand flags 80)) (mep2:out "Mesh/polyface: raw coordinates only."))
              ((/= 0 (logand flags 8)) (mep2:val "Vertex_WCS" p))
              (T (mep2:point "Vertex" (list (car p) (cadr p) (caddr (cdr (assoc 10 d)))) e)))))
        (setq sub (entnext sub)))
      (setq pts (reverse pts))
      (mep2:val "FirstVertex_RAW" (car pts))
      (mep2:val "LastVertex_RAW" (last pts)))
    ((= typ "INSERT")
      (mep2:val "BlockName" (cdr (assoc 2 d)))
      (mep2:point "Insertion" (cdr (assoc 10 d)) e)
      (foreach pair d
        (if (member (car pair) '(41 42 43 50 70 71 44 45))
          (mep2:val "BlockTransform_or_Array_DXF" pair)))
      (setq b (tblsearch "BLOCK" (cdr (assoc 2 d))))
      (mep2:val "BlockFlags_DXF70" (cdr (assoc 70 b)))
      (mep2:val "XrefPath_DXF1" (cdr (assoc 1 b)))
      (if (= 1 (cdr (assoc 66 d)))
        (progn
          (setq sub (entnext e))
          (while (and sub (/= "SEQEND" (cdr (assoc 0 (setq sd (entget sub))))))
            (if (= "ATTRIB" (cdr (assoc 0 sd)))
              (progn
                (mep2:val "AttributeTag" (cdr (assoc 2 sd)))
                (mep2:val "AttributeText_RAW" (mep2:text sd))
                (mep2:val "AttributeLayer" (cdr (assoc 8 sd)))
                (mep2:val "Attribute_DXF" sd)
                (if full (mep2:text-layout sub sd (cdr (assoc 5 d)) "AttributeLayout."))))
            (setq sub (entnext sub)))))
      ; Constant attribute definitions are in block-local coordinates.
      (setq sub (cdr (assoc -2 b)))
      (while sub
        (setq sd (entget sub))
        (if (and (= "ATTDEF" (cdr (assoc 0 sd)))
                 (/= 0 (logand 2 (cdr (assoc 70 sd)))))
          (mep2:val "ConstantAttributeDefinition_BLOCK_LOCAL" sd))
        (setq sub (entnext sub)))
      (mep2:out "Nested block geometry is NOT expanded; block-local geometry is not counted as ModelSpace entities.")
      (if full (mep2:dynamic e)))
    ((member typ '("TEXT" "MTEXT"))
      (mep2:val "Text_RAW" (mep2:text d))
      (if (= typ "MTEXT")
        (mep2:val "Insertion_WCS" (cdr (assoc 10 d)))
        (progn
          (mep2:point "Insertion" (cdr (assoc 10 d)) e)
          (mep2:point "Alignment" (cdr (assoc 11 d)) e)))
      (mep2:out "Text formatting/field expressions are preserved, not evaluated.")
      (if full (mep2:text-layout e d nil "")))
    (T
      (mep2:out "UNPARSED_TYPE: identity and non-binary DXF fields only; no semantic inference.")
      (foreach pair d
        (if (not (member (car pair) '(310 311 312 313 314 315 316 317 318 319)))
          (mep2:val "Raw_DXF" pair))))))

(defun mep2:read (full / *error* mep2:fh outputPath outputFileName proceed existing stage row layers layer ss i e d typ counts entry total errors result root filename allcounts)
  (defun *error* (msg)
    (princ (strcat "\nEntity acquisition stopped at stage [" (if stage stage "initialization") "]: " msg))
    (if mep2:fh
      (progn
        (vl-catch-all-apply 'write-line (list (strcat "INCOMPLETE_REPORT: " msg) mep2:fh))
        (vl-catch-all-apply 'close (list mep2:fh))
        (setq mep2:fh nil)))
    (princ))
  (vl-catch-all-apply 'vl-load-com nil)
  ; Use this script's folder when findfile can resolve it; otherwise choose manually.
  (setq root (findfile "Test-AutoCADEntities.lsp"))
  (setq filename (if full "MEP-full-entity-report.txt" "MEP-entity-report.txt"))
  (setq stage "getfiled")
  (setq outputPath (getfiled (strcat "Save read-only snapshot as " filename)
    (if root
      (strcat (vl-filename-directory root) "/local_test_data/" filename)
      (strcat (getvar "DWGPREFIX") filename)) "txt" 1))
  (setq proceed outputPath stage "path-validation")
  ; Only full mode adds absolute-path validation; never reconstruct the selection.
  (if (and full outputPath)
    (progn
      (princ (strcat "\nOutputPath = " outputPath))
      (if (not (or
        (and (>= (strlen outputPath) 3) (= (substr outputPath 2 1) ":") (member (substr outputPath 3 1) '("/" "\\")))
        (= (substr outputPath 1 2) "\\\\")
        (= (substr outputPath 1 2) "//")))
        (progn (princ "\nRejected: absolute output path required.") (setq proceed nil)))))
  (if proceed
    (progn
      (setq stage "filename-validation")
      (setq outputFileName (strcat (vl-filename-base outputPath) (if (vl-filename-extension outputPath) (vl-filename-extension outputPath) "")))
      (if full (princ (strcat "\nOutputFileName = " outputFileName)))
      (setq stage "existence-check")
      (if full
        (progn
          (setq existing (findfile outputPath))
          (princ (strcat "\nExists = " (if existing "YES" "NO")))
          (if existing
            (progn (princ (strcat "\nExisting snapshot protected:\n" existing)) (setq proceed nil)))))))
  (if proceed (setq stage "filename-validation"))
  (if proceed
    (if (/= (strcase outputFileName) (strcase filename))
      (princ (strcat "\nCancelled: report filename must be " filename))
      (progn
        (setq stage "open-output")
        (setq mep2:fh (if (= 0 (getvar "LISPSYS")) (open outputPath "w") (open outputPath "w" "utf8-bom")))
        (if (not mep2:fh) (progn (princ "\nCannot open report file.") (exit)))
        (mep2:out "MEP-Manager phase 2: READ-ONLY ENTITY REPORT")
        (if full
          (progn
            (mep2:val "ExtractorVersion" "2.3-text-layout-metadata")
            (mep2:val "TextLayoutMetadata" "TEXT/MTEXT/attached ATTRIB; raw DXF plus optional WCS bbox; no layout interpretation")
            (mep2:val "BoundingBoxPolicy" "best-effort getter; independent status; failures do not increment ReadErrorCount")
            (mep2:val "DynamicBlockMetadata" "top-level INSERT getter-only; independent per-field status; no geometry expansion")
            (mep2:val "AcquisitionMode" "ModelSpaceTopLevelAllLayers")
            (mep2:val "AcquiredAtLocal" (getvar "CDATE"))
            (mep2:val "ModelSpaceTopLevel" "included")
            (mep2:val "AllLayers" "included; including off/frozen")
            (mep2:val "AttachedATTRIB" "included for selected INSERT; raw DXF")
            (mep2:val "ConstantATTDEF" "direct block definition only; block-local raw DXF")
            (mep2:val "BlockDefinitionRecursiveExpansion" "not included")
            (mep2:val "NestedBlocks" "not expanded")
            (mep2:val "XrefContents" "not expanded")
            (mep2:val "PaperSpaceLayouts" "not included")
            (mep2:val "ProxySemanticRecovery" "not included; identity/non-binary DXF only")
            (mep2:val "TableSemanticExtraction" "not included; raw non-binary DXF may contain cell values")
            (mep2:val "SnapshotPolicy" "new snapshot; no automatic evidence or confirmation migration")
            (mep2:val "FingerprintPolicy" "SHA-256 exact saved bytes externally; timestamp and runtime DXF references can differ between runs")))
        (mep2:val "DWG" (strcat (getvar "DWGPREFIX") (getvar "DWGNAME")))
        (mep2:val "INSUNITS" (getvar "INSUNITS"))
        (mep2:out "Coordinates are drawing units; no length calculation. No DWG write/save/cleanup/conversion.")
        (mep2:out "Real-valued coordinates use decimal notation with 6 fractional digits, including nested DXF records.")
        (if full
          (mep2:out "Scope: ModelSpace top-level entities on ALL layers; no professional candidate filtering. Not a complete DWG extraction.")
          (progn
            (mep2:out "Scope: ModelSpace top-level entities on candidate layers, including off/frozen layers.")
            (mep2:out "Layer matching: EQUIP-*, E-*, EP-*, CABLETRAY_*, WIRE-*, LWIRE, TEL_TEXT, TEL_SYMB; also prefixed names.")))
        (mep2:out "Nested geometry/XREF contents are NOT recursively scanned. Zero does not prove absence in nested blocks.")
        (mep2:out "ObjectName uses optional in-process ActiveX; failure is recorded without stopping native DXF reads.")
        (setq stage "entity-acquisition")
        (setq row (tblnext "LAYER" T) total 0 errors 0)
        (while row
          (setq layer (cdr (assoc 2 row)))
          (if (or full (wcmatch (strcase layer) "*EQUIP-*,*E-*,*EP-*,*CABLETRAY_*,*WIRE-*,*LWIRE,*TEL_TEXT,*TEL_SYMB"))
            (setq layers (cons layer layers)))
          (setq row (tblnext "LAYER")))
        (foreach layer (reverse layers)
          (princ (strcat "\nReading layer: " layer))
          (mep2:val "LAYER_BEGIN" layer)
          ; Escape wildcard characters so ssget matches this exact layer name.
          (setq root "")
          (foreach i (vl-string->list layer)
            (if (member i '(35 64 46 42 63 126 91 93 45 44 96))
              (setq root (strcat root "`")))
            (setq root (strcat root (chr i))))
          (setq ss (ssget "_X" (list (cons 8 root) '(410 . "Model"))))
          (setq i 0 counts nil)
          (if ss
            (repeat (sslength ss)
              (setq e (ssname ss i) i (1+ i))
              (setq d (vl-catch-all-apply 'entget (list e)))
              (if (or (vl-catch-all-error-p d) (not d))
                (progn
                  (setq errors (1+ errors))
                  (mep2:val "ENTITY_UNREADABLE" (vl-prin1-to-string e))
                  (mep2:val "Error" (if (vl-catch-all-error-p d) (vl-catch-all-error-message d) "entget returned nil")))
                (progn
                  (setq typ (cdr (assoc 0 d)) entry (assoc typ counts))
                  (setq counts (if entry (subst (cons typ (1+ (cdr entry))) entry counts) (cons (cons typ 1) counts)))
                  (if full
                    (progn
                      (setq entry (assoc typ allcounts))
                      (setq allcounts (if entry (subst (cons typ (1+ (cdr entry))) entry allcounts) (cons (cons typ 1) allcounts)))))
                  (mep2:val "EntityHandle" (cdr (assoc 5 d)))
                  (mep2:val "DXF_Type" typ)
                  (mep2:val "Layer" (cdr (assoc 8 d)))
                  (setq result (vl-catch-all-apply 'mep2:details (list e d)))
                  (if (vl-catch-all-error-p result)
                    (progn (setq errors (1+ errors))
                      (mep2:val "DETAIL_ERROR" (vl-catch-all-error-message result)))))))
            )
          (setq total (+ total i))
          (mep2:val "LayerEntityCount" i)
          (mep2:val "TypeCounts_DXF" (reverse counts))
          (mep2:out "LAYER_END")
          (setq ss nil))
        (mep2:val (if full "ObservedLayerCount" "CandidateLayerCount") (length layers))
        (if full (mep2:val "GlobalTypeCounts_DXF" (reverse allcounts)))
        (mep2:val "SelectedEntityTotal" total)
        (mep2:val "ReadErrorCount" errors)
        (mep2:out "END_OF_REPORT: scan finished. Inspect errors and scope limitations before interpreting results.")
        (setq stage "close-output")
        (close mep2:fh) (setq mep2:fh nil)
        (princ (strcat "\nReport saved: " outputPath "\nEntities: " (itoa total) "; errors: " (itoa errors)))))
    (princ "\nCancelled. No report written."))
  (princ))
(defun c:MEPENTITYREAD () (mep2:read nil))
(defun c:MEPFULLREAD () (mep2:read T))
(princ "\nLoaded. MEPENTITYREAD: candidate layers. MEPFULLREAD: all-layer ModelSpace top-level snapshot.")
(princ)
