const test = require('node:test');
const assert = require('node:assert/strict');
const MEP = require('../core.js');
const item = changes => ({ id: 'i1', name: '给水管', spec: 'DN25', system: '给水', unit: 'm', base: 10, copies: 2, extra: 3, allowance: 5, price: 12.5, location: '1 层', note: '', source: null, ...changes });
const backup = () => ({ version: 1, projects: [{ id: 'p1', name: '项目', location: '', drawings: [{ id: 'd1', name: '图纸', width: 100, height: 100, data: 'data:image/png;base64,AAAA', scale: .1 }], items: [item({ base: 1, source: { drawingId: 'd1', kind: 'length', points: [{ x: 0, y: 0 }, { x: 10, y: 0 }], scale: .1 } })], cash: [] }] });
test('折线测量累计每一段，而非起终点直线距离', () => assert.equal(MEP.distance([{ x: 0, y: 0 }, { x: 3, y: 0 }, { x: 3, y: 4 }]), 7));
test('标定与缩放无关：100 像素对应 3.6 米', () => assert.equal(MEP.calibrate([{ x: 20, y: 30 }, { x: 120, y: 30 }], 3.6), .036000000000000004));
test('重合标定点和无效实际距离必须拒绝', () => { assert.throws(() => MEP.calibrate([{ x: 0, y: 0 }, { x: 0, y: 0 }], 1)); assert.throws(() => MEP.calibrate([{ x: 0, y: 0 }, { x: 10, y: 0 }], 0)); });
test('倍数、预留、备料损耗分开计算，金额精确到分', () => { const c = MEP.calculate(item()); assert.equal(c.quantity, 23); assert.ok(Math.abs(c.purchase - 24.15) < 1e-10); assert.equal(c.cost, 301.88); });
test('备料损耗不改变实际工程量', () => assert.equal(MEP.calculate(item({ allowance: 50 })).quantity, MEP.calculate(item({ allowance: 0 })).quantity));
test('不填单价时仍保留数量，金额为零', () => { const c = MEP.calculate(item({ price: 0 })); assert.equal(c.cost, 0); assert.equal(c.quantity, 23); });
test('不允许负数量、分数份数、非有限数和过大损耗', () => { for (const changes of [{ base: -1 }, { copies: 1.5 }, { base: Infinity }, { allowance: 101 }, { price: NaN }, { copies: 0 }]) assert.throws(() => MEP.calculate(item(changes))); });
test('不把不同规格、单位、专业混在一起汇总', () => assert.equal(MEP.summarize([item(), item({ spec: 'DN32' }), item({ unit: '个' }), item({ system: '消防' })]).length, 4));
test('同材料不同单价逐笔算钱，不使用平均单价错误重算', () => { const g = MEP.summarize([item({ base: 1, copies: 1, extra: 0, allowance: 0, price: 10 }), item({ base: 2, copies: 1, extra: 0, allowance: 0, price: 20 })])[0]; assert.equal(g.quantity, 3); assert.equal(g.cost, 50); });
test('汇总保留小数精度，不先截断每笔长度', () => { const i = item({ base: .0004, copies: 1, extra: 0 }); assert.ok(Math.abs(MEP.summarize([i, i, i])[0].quantity - .0012) < 1e-12); });
test('CSV 正确处理中文、逗号、引号、换行和公式注入', () => { const csv = MEP.csv([['中文', 'A,B', 'a"b', 'a\nb', '=1+1', ' @SUM(A1)', '-2']]); assert.ok(csv.startsWith('\uFEFF')); assert.ok(csv.includes('"A,B"')); assert.ok(csv.includes('"a""b"')); assert.ok(csv.includes('"a\nb"')); assert.ok(csv.includes("\"'=1+1\"")); assert.ok(csv.includes("\"' @SUM(A1)\"")); });
test('完整备份有效且保留历史比例，新标定不改写原测量', () => { const b = backup(); b.projects[0].drawings[0].scale = .2; assert.equal(MEP.validateBackup(b).projects[0].items[0].base, 1); });
test('备份拒绝丢失图纸、重复编号和越界点', () => { let b = backup(); b.projects[0].drawings = []; assert.throws(() => MEP.validateBackup(b)); b = backup(); b.projects[0].items[0].id = 'p1'; assert.throws(() => MEP.validateBackup(b)); b = backup(); b.projects[0].items[0].source.points[1].x = 101; assert.throws(() => MEP.validateBackup(b)); });
test('备份拒绝外部图片和可执行 SVG', () => { for (const data of ['https://example.com/a.png', 'data:image/svg+xml;base64,AAAA']) { const b = backup(); b.projects[0].drawings[0].data = data; assert.throws(() => MEP.validateBackup(b)); } });
test('备份中图纸测量结果必须与测量点匹配', () => { const b = backup(); b.projects[0].items[0].base = 999; assert.throws(() => MEP.validateBackup(b)); });
test('点设备数量来自测量点，与长度比例无关', () => { const b = backup(); b.projects[0].items[0] = item({ base: 2, unit: '个', source: { drawingId: 'd1', kind: 'count', scale: null, points: [{ x: 10, y: 10 }, { x: 20, y: 20 }] } }); assert.doesNotThrow(() => MEP.validateBackup(b)); });
test('备份拒绝伪装成数字的字符串，防止恢复后金额导出失败', () => { const b = backup(); b.projects[0].cash.push({ id: 'c1', name: '采购', type: 'expense', date: '2026-09-12', amount: '12.50' }); assert.throws(() => MEP.validateBackup(b)); });
test('过大单笔金额被拒绝，避免超出可靠货币计算范围', () => assert.throws(() => MEP.calculate(item({ base: 1e9, price: 1e8, copies: 1, extra: 0 }))));
